language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t jfrancisco777/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jfrancisco777/docker-react yarn test
