language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t jfrancisco777/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jfrancisco777/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-638337117025"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
